### ISSUE TITLE
Service shouldnt 404 on `/` endpoint

### ISSUE THREAD

**Issue by Pothulapati** [servicemeshinterface/smi-metrics#22]
Right now the APIService only serves requests from `/apis/group/version`, and 404's on `/` .

We can do something like what kubernetes does, on `/` and provide information about sub resources that users can ask about! That would provide awesome user experience on the SMI-Metrics API

![Screenshot 2019-07-09 08 23 36](https://user-images.githubusercontent.com/7892868/60902364-194bd780-a28d-11e9-9f81-15e259deeed9.png)

**Comment by tharun208** [comment]
Hi @Pothulapati, I like to work on this

**Comment by Pothulapati** [comment]
@tharun208 go ahead! :+1:
