### ISSUE TITLE
Support for edges at Kind level

### ISSUE THREAD

**Issue by daxmc99** [servicemeshinterface/smi-metrics#45]
There are common situations where you need to request edge information across a Kind within a namespace. For example, if I want to create an edges graph I need information about every deployment in the namespace. Right now, the only way to do this is to request edges for each kind found in the namespace. Instead, I propose we add a special edges endpoint. 

For example, `/apis/metrics.smi-spec.io/v1alpha1/namespaces/default/deployments/` could have the endpoint of an edge of `/apis/metrics.smi-spec.io/v1alpha1/namespaces/default/deployments/$edges`.  The special character is required to avoid any overlap with a possible resource name. 

Any thoughts on this proposal?

**Comment by daxmc99** [comment]
cc @Pothulapati

**Comment by grampelberg** [comment]
I think this'll break RBAC unfortunately.

**Comment by daxmc99** [comment]
Do you mean in the way that RBAC is currently implemented in smi-metrics today or in the broader sense that k8s RBAC cannot accommodate this? 
 
A user who has the ability to `[ get , list]` over a namespace should be able to view metrics for that namespace.

**Comment by grampelberg** [comment]
K8s RBAC. At the moment `edges` is a sub-resource and treated as a separate permission.

**Comment by Pothulapati** [comment]
@daxmc99 One of the thing I have been advocating recently is a `svc-graph` endpoint through which graphs can be built. Resource level should be passed as a parameter and it would show graphs for those resources. Something like `svc-graph/pods`, etc. WDYT?
This would also let us separate it, and not break k8s RBAC for edges.

@grampelberg

**Comment by grampelberg** [comment]
@Pothulapati we'll need to think up a different RBAC scheme, which sounds reasonable ... just need to get it together.

FWIW, I'm still not sold that the API needs to support this functionality. It feels like something that is easier done in a client library. There's obviously tradeoffs there, but for V1 it feels like a better solution to introduce the complexity outside the API.

**Comment by daxmc99** [comment]
Right now, it looks like the only way to construct an edge graph for a namespace requires making `n -1` api calls to get the edges for each deployment. It seems like quite a bit of duplicated work to request edges and then deduplicate the data for the graph.

**Comment by daxmc99** [comment]
The problem I am trying to solve is to be able to draw an edges graph for something like deployments. Right now, to make an edges graph across all deployments in a namespace it looks like I need to  `n - 1` calls to the metrics API to discover the full mesh
