### ISSUE TITLE
Fix Charts directory

### ISSUE THREAD

**Issue by Pothulapati** [servicemeshinterface/smi-metrics#48]
Currently we publish installation helm charts as a github release, but the charts in the repo are templated and thus not usable directly causing confusions like https://github.com/deislabs/smi-metrics/issues/42 ,etc

 I think the best way is to update the release workflow to also change relevant files in the repo, so that users can directly use the charts dir when they clone the repo.

**Comment by grampelberg** [comment]
I feel pretty strongly that CI should not modify the source. Can we put some tooling and instructions in place instead? A simple `run make chart` instruction with a little bit of "you forgot to do X" would probably be good enough.
