### ISSUE TITLE
Telemetry v2 for Istio

### ISSUE THREAD

**Issue by Pothulapati** [servicemeshinterface/smi-metrics#55]
Now Istio moved a two new telemetry model, where the metrics are not configurable yet and Istio only gives back some default metrics. 

There are also some changes in the default metrics like https://github.com/weaveworks/flagger/issues/478

This can act like a placeholder Issue for the Telemetry v2 Discussion

**Comment by Pothulapati** [comment]
I have been trying to get this done. I have a initial draft based at  https://github.com/Pothulapati/smi-metrics/pull/new/istio-v2
I have a blocker with `*_owner` label, and reached the istio slack.Will try resolution once I get back a reply. 

Feel free to comment on the issue, if there are any suggestions.

**Comment by nveenjain** [comment]
Hi @Pothulapati , any updates related to this issue?

**Comment by Pothulapati** [comment]
Hey @nveenjain, I have been pretty busy recently so wasn't able to get this done though it dosen't seem to have any kind of blockers.

If you are interested, Feel free to take this up. Happy to help :)
