### ISSUE TITLE
TrafficMesh object referenced in TrafficMetrics

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-metrics#70]
In, `https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-metrics.md#example-implementation`: 
![Screen Shot 2020-04-17 at 8 59 00 AM](https://user-images.githubusercontent.com/1497123/79571876-f22afd80-8089-11ea-8ecb-75f1f780effb.jpg)

Is that supposed to be `TrafficMetrics`?

**Comment by Pothulapati** [comment]
Yep, It should be `TrafficMetrics`

**Comment by michelleN** [comment]
resolved in spec. thanks!
